# Explicitly specify Python runtime
[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

# Force Python detection
[variables]
NIXPACKS_NODE_VERSION = "none"