[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m uvicorn backend.main:app --host 0.0.0.0 --port 8080"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10